name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json tokens/global.json  global,light,main1 light,main1
      # Create a light theme
      - run: npx token-transformer tokens.json tokens/light.json light
      # Create a dark theme
      - run: npx token-transformer tokens.json tokens/dark.json dark
      # Create a main1 theme, include light
      - run: npx token-transformer tokens.json tokens/main1.json main1,light light
      # Create a main2 theme, include light
      - run: npx token-transformer tokens.json tokens/main2.json main2,light light
      # Convert tokens according to Style Dictionary config
      - run: node build.js
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
